-- V1: 기존 스키마 baseline (2026-07-16)
-- Hibernate(ddl-auto: update)가 만들어 둔 실제 프로덕션 스키마를 information_schema 조회로
-- 그대로 옮긴 것. 이미 테이블이 있는 DB(현 Railway)는 baseline-on-migrate에 의해
-- 이 파일을 건너뛰고 버전 1로 기록만 남긴다. 새 DB에서는 이 파일이 실행된다.
--
-- 제약조건 이름은 Hibernate 자동생성 난수 이름(fknjuop..., uk6dot...) 대신 읽기 쉬운
-- 이름을 썼다. 기존 DB와 이름이 달라지지만 Hibernate validate는 이름을 검사하지 않는다.

create table users (
    id            bigint generated by default as identity primary key,
    email         varchar(255) not null,
    password_hash varchar(255) not null,
    display_name  varchar(255) not null,
    role          varchar(255) not null,
    created_at    timestamp(6) with time zone not null,
    constraint uq_users_email unique (email),
    constraint users_role_check check (role in ('CLIENT', 'ADVISOR'))
);

create table accounts (
    id            bigint generated by default as identity primary key,
    user_id       bigint not null,
    name          varchar(255) not null,
    sub_label     varchar(255) not null,
    short_name    varchar(255) not null,
    value         bigint not null,
    ytd_label     varchar(255) not null,
    up            boolean not null,
    display_order integer not null,
    constraint fk_accounts_user foreign key (user_id) references users (id)
);

create table holdings (
    id            bigint generated by default as identity primary key,
    user_id       bigint not null,
    ticker        varchar(255) not null,
    security_name varchar(255) not null,
    account_label varchar(255) not null,
    qty_label     varchar(255) not null,
    price         numeric(12, 2),
    value         bigint not null,
    day_label     varchar(255) not null,
    day_trend     integer not null,
    gain_label    varchar(255) not null,
    gain_up       boolean not null,
    display_order integer not null,
    constraint fk_holdings_user foreign key (user_id) references users (id)
);

create table activity (
    id                  bigint generated by default as identity primary key,
    user_id             bigint not null,
    label               varchar(255) not null,
    date_label          varchar(255) not null,
    amount_label        varchar(255) not null,
    masked_amount_label varchar(255) not null,
    color_label         varchar(255) not null,
    display_order       integer not null,
    constraint fk_activity_user foreign key (user_id) references users (id)
);

create table portfolio_snapshots (
    id                      bigint generated by default as identity primary key,
    user_id                 bigint not null,
    day_change_label        varchar(255) not null,
    day_change_masked_label varchar(255) not null,
    ytd_return_label        varchar(255) not null,
    income_ytd              bigint not null,
    cash_available          bigint not null,
    cash_apy_label          varchar(255) not null,
    constraint uq_portfolio_snapshots_user unique (user_id),
    constraint fk_portfolio_snapshots_user foreign key (user_id) references users (id)
);

create table chat_conversations (
    id         bigint generated by default as identity primary key,
    client_id  bigint not null,
    created_at timestamp(6) with time zone not null,
    constraint uq_chat_conversations_client unique (client_id),
    constraint fk_chat_conversations_client foreign key (client_id) references users (id)
);

create table chat_messages (
    id              bigint generated by default as identity primary key,
    conversation_id bigint not null,
    sender_id       bigint not null,
    content         varchar(4000) not null,
    sent_at         timestamp(6) with time zone not null,
    constraint fk_chat_messages_conversation foreign key (conversation_id) references chat_conversations (id),
    constraint fk_chat_messages_sender foreign key (sender_id) references users (id)
);
