-- V4: /insights 뉴스 서비스 — 외부 RSS 수집 기사 저장 (2026-07-18)
create table news_articles (
    id           bigint generated by default as identity primary key,
    source       varchar(100)  not null,
    category     varchar(30)   not null,
    title        varchar(500)  not null,
    summary      varchar(1000),
    url          varchar(1000) not null,
    published_at timestamp(6) with time zone,
    fetched_at   timestamp(6) with time zone not null,
    hidden       boolean not null default false,
    -- 재수집 시 같은 기사를 두 번 넣지 않기 위한 중복 방지 키
    constraint uq_news_articles_url unique (url),
    constraint news_articles_category_check
        check (category in ('MARKETS', 'BUSINESS', 'TAX_ACCOUNTING'))
);
